
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VentasAP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Producto
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Producto()
    {

        this.StockLocal = new HashSet<StockLocal>();

    }


    public int id_producto { get; set; }

    public string codigo { get; set; }

    public string nombre { get; set; }

    public int precio_compra { get; set; }

    public int precio_venta { get; set; }

    public string descripcion { get; set; }

    public int id_marca { get; set; }

    public int id_categoria { get; set; }



    public virtual Categoria Categoria { get; set; }

    public virtual Marca Marca { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StockLocal> StockLocal { get; set; }

}

}
