
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VentasAP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Venta
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Venta()
    {

        this.DetalleVenta = new HashSet<DetalleVenta>();

    }


    public int id_venta { get; set; }

    public int total { get; set; }

    public System.DateTime fecha { get; set; }

    public Nullable<int> id_cliente { get; set; }

    public int id_user { get; set; }



    public virtual Cliente Cliente { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }

    public virtual User User { get; set; }

}

}
